#!/usr/bin/env bash

usage="Usage: subprepare (assignment name)"

username=morri2wj
class=cs361
semester=f23
prof=kirkpams

name=$1 # name of assignment, first arg
if [[ "$#" -eq 0 ]]; then
    echo "Specify a lab/project name!"
    echo $usage
    exit 1
fi

if [[ "$#" -gt 1 ]]; then
    echo "Too many args!"
    echo $usage
    exit 1
fi 

rootdir=/cs/students/$class/$semester/$prof
if [[ ! -d $rootdir ]]; then
    echo "Content root directory not found: $rootdir"
    exit 1
fi

subroot=$rootdir/submit/$username
if [[ ! -d "$subroot" ]]; then
    echo "Submission parent directory $subroot not found."
    exit 1
fi

subpath=$subroot/$name
if [[ -d "$subpath" ]]; then
    echo "Submission directory $subpath already exists!"
    echo "Exiting to prevent overwrite."
    exit 1
fi

tarpath=$rootdir/src/$name.tar.gz
if [[ ! -f "$tarpath" ]]; then
    echo "File not found: $tarpath"
    echo $usage
    exit 1
fi

cd $subroot
tar xvzf $tarpath

