#!/usr/bin/env bash

username=morri2wj
name=$1

class=cs361
semester=f23
prof=kirkpams
rootdir=/cs/students/$class/$semester/$prof

if [[ ! -d $rootdir ]]; then
    echo "Content root directory not found: $rootdir"
    exit 1
fi

tarpath=$rootdir/src/$name.tar.gz
if [[ ! -f "$tarpath" ]]; then
    echo "File not found: $tarpath"
    exit 1
fi

cd /cs/students/cs361/f23/kirkpams/submit/$username

